---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
  app: app
spec:
  replicas: 1
  selector:
    metaLabels:
    app: app
  template:
    metadata:
      labels:
        app: app
      spec:
        container:
         - name:
           image: trydomain/testprofileapp
           ports:
             - name: app-port
               containerPort: 8080
        initContainers:
          - name: init-mydb
            image: busybox
            commad: ['sh','-c','until nslookup vprodb; do echo waiting for mydb; sleep 2; done;']
          - name: init-memcache
            image: busybox
            commad: [ 'sh','-c','until nslookup vprocache01; do echo waiting for mydb; sleep 2; done;' ]
